### ISSUE TITLE
Broken Link in Documentation for Code Sandbox Config File

### ISSUE THREAD

**Issue by kr1st1nagr03g3r** [codesandbox/docs#83]
Hi there, good morning. I found a small issue with a broken link in your documentation:

Steps to replicate:
1) Navigate to: https://codesandbox.io/docs/faq#can-i-open-the-terminal-or-console-or-test-panel-instead-of-the-browser-in-a-sandbox
2) Click on the link "sandbox config file" 
3) https://codesandbox.io/docs/configuration#sandbox-configuration renders a broken link.

Thank you and have a great day!

**Comment by tristandubbeld** [comment]
Thanks for raising this issue @kr1st1nagr03g3r! I'm working on a PR to fix this and a few other broken links that came up thanks to your comment. Please let us know if anything else pops up :)

And a great day to you, too!
